### ISSUE TITLE
Why we have node_modules in repo?

### ISSUE THREAD

**Issue by piecioshka** [feyzayigiter/RESTful-PostRequest#1]
`node_modules` is a directory which is generated by command `npm install` / `yarn install`.

It will look different on macos, windows and linux.

Probably better will be to create in each project file `.gitignore` with content:

```md
node_modules/
```

So then directory `node_modules` will be never in Git repository.

Good luck Feyza! 🤞

**Comment by feyzacan** [comment]
Hello Piotr! 
I made the necessary corrections.
Thanks a lot for your warning 🙏

**Comment by piecioshka** [comment]
Awesome! 🏆
